
mender-qa:success:
  tags:
    - hetzner-amd-beefy
  stage: .post
  dependencies: []
  when: on_success
  # Keep overhead low by using a small image with curl preinstalled.
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/alpine/curl
  before_script:
    - apk --update add jq
  script:
    - $CI_PROJECT_DIR/scripts/github_pull_request_status success "mender-qa pipeline passed" $CI_PIPELINE_URL ci/mender-qa

mender-qa:failure:
  tags:
    - hetzner-amd-beefy
  stage: .post
  dependencies: []
  when: on_failure
  # Keep overhead low by using a small image with curl preinstalled.
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/alpine/curl
  before_script:
    - apk --update add jq
  script:
    - $CI_PROJECT_DIR/scripts/github_pull_request_status failure "mender-qa pipeline failed" $CI_PIPELINE_URL ci/mender-qa

trigger:mantra:
  stage: .post
  inherit:
    variables: false
  trigger:
    branch: master
    project: Northern.tech/Mender/mantra
    strategy: depend
  rules:
    - if: $NIGHTLY_BUILD == "true"
      when: always
